/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.Vista;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FRM_Canciones extends javax.swing.JFrame 
{

    /**
     * Creates new form FRM_Canciones
     */
    public FRM_Canciones() 
    {
        initComponents();
        
        getContentPane().setBackground(Color.green);
    }
    
    
    public PanelDatosCancion getPanelDatos()
    {  
        return this.panelDatosCancion1;
    }
    
    public PanelBotones getPanelBotones()
    {  
        return this.panelBotones2;
    }
    
    public void setEscuchadores(ActionListener manejador)
    {
      this.panelBotones2.escuchadorBotones(manejador);
      this.panelDatosCancion1.escuchador(manejador);
      
    }
    
    
    public void mensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null, mensaje);
        
      
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosCancion1 = new ucr.ac.cr.Vista.PanelDatosCancion();
        panelBotones2 = new ucr.ac.cr.Vista.PanelBotones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosCancion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotones2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.Vista.PanelBotones panelBotones2;
    private ucr.ac.cr.Vista.PanelDatosCancion panelDatosCancion1;
    // End of variables declaration//GEN-END:variables


    


}
