/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.Vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FRM_Artistas extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Artistas
     */
    public FRM_Artistas() {
        initComponents();
    }
    
    public PanelArtista getPanelDatosArtista()
    {  
        return this.panelArtista1;
    }
    
    public PanelBotones getPanelBotones()
    {  
        return this.panelBotones1;
    }
    
    public void setEscuchadores(ActionListener manejador)
    {
      this.panelBotones1.escuchadorBotones(manejador);
      this.panelArtista1.escuchador(manejador);
      
    }
    
    
    public void mensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null, mensaje);
        
      
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones1 = new ucr.ac.cr.Vista.PanelBotones();
        panelArtista1 = new ucr.ac.cr.Vista.PanelArtista();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBotones1.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(panelBotones1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.Vista.PanelArtista panelArtista1;
    private ucr.ac.cr.Vista.PanelBotones panelBotones1;
    // End of variables declaration//GEN-END:variables
}
