/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.Vista;

import java.awt.event.ActionListener;

/**
 *
 * @author Usuario
 */
public class PanelBotones extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() 
    {
        initComponents();
    }
    
    public void escuchadorBotones(ActionListener manejador)
    {
      this.btGuardar.addActionListener(manejador);
      this.btEditar.addActionListener(manejador);
      this.btEliminar.addActionListener(manejador);
      this.btMenu.addActionListener(manejador);
      this.btnReporte.addActionListener(manejador);
    }
    
    
    public void activarBotones(boolean estado)
    {
     this.btEditar.setEnabled(estado);
     this.btEliminar.setEnabled(estado);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGuardar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btMenu = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 51));

        btGuardar.setBackground(new java.awt.Color(0, 255, 0));
        btGuardar.setText("agregar");
        btGuardar.setActionCommand("Agregar");
        btGuardar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btGuardarItemStateChanged(evt);
            }
        });

        btEliminar.setBackground(new java.awt.Color(0, 255, 51));
        btEliminar.setText("eliminar");
        btEliminar.setActionCommand("Eliminar");
        btEliminar.setEnabled(false);
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        btEditar.setBackground(new java.awt.Color(0, 255, 51));
        btEditar.setText("modificar");
        btEditar.setActionCommand("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btMenu.setBackground(new java.awt.Color(0, 255, 51));
        btMenu.setText("Volver");
        btMenu.setToolTipText("");
        btMenu.setActionCommand("Salir");

        btnReporte.setText("Reporte");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btEditar)
                .addGap(36, 36, 36)
                .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporte)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMenu)
                    .addComponent(btnReporte))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
      
        
    }//GEN-LAST:event_btEliminarActionPerformed

    private void btGuardarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btGuardarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarItemStateChanged

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditarActionPerformed

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btnReporte;
    // End of variables declaration//GEN-END:variables
}
